### ISSUE TITLE
Chapter 2.3, ex3 and ex4 don't work because (==>) is not in scope as a haskell value.

### ISSUE THREAD

**Issue by chowells79** [ucsd-progsys/liquidhaskell-tutorial#13]
The examples look like this:

    {-@ ex3 :: Bool -> Bool -> TRUE @-}
    ex3 a b = (a && b) ==> a

    {-@ ex4 :: Bool -> Bool -> TRUE @-}
    ex4 a b = (a && b) ==> b

When attempting to verify the first of those, I get:

    **** ERROR: Invalid Source *****************************************************

     tutorial-ch2.hs:19:20-22: Error: GHC Error
         Not in scope: ‘==>’
    Perhaps you meant ‘==’ (imported from Prelude)

What am I missing?  Just adding the definition of `(==>)` from earlier in the chapter doesn't fix it.  I end up getting:

    **** UNSAFE ********************************************************************

     tutorial-ch2.hs:19:11-24: Error: Liquid Type Mismatch
       Inferred type
         VV : Bool
  
       not a subtype of Required type
         VV : Bool | Prop VV
  
       In Context
         VV : Bool

I assume this is because liquid haskell doesn't look inside definitions, and just uses `Bool -> Bool -> Bool` as the type for `(==>)` when it lacks an accurate liquid haskell annotation.

**Comment by ranjitjhala** [comment]
Yikes this is my bad. I will fix the parser! In the meantime just use =>
For implies!

**Comment by ranjitjhala** [comment]
@chowells79 did you install from hackage or github? This issue is fixed in master so should be fine if you rebuild from there. Apologies for not updating hackage together with the tutorial!

@gridaphobe I think we should do a new release on hackage, perhaps after @nikivazou is done with they recent slew of bug fixes? (Thanks!)

**Comment by chowells79** [comment]
I installed from hackage. I'll give it a shot with a build from github later on and report.

**Comment by chowells79** [comment]
Same error on a build from github.  I suspect you may have misdiagnosed the problem.  The example shows using (==>) in the term-level expression, which isn't defined.

**Comment by ranjitjhala** [comment]
Sorry! Are you using this file from the tutorial src/ directory 

https://github.com/ucsd-progsys/liquidhaskell-tutorial/blob/master/src/02-logic.lhs#L132

As you can see it's defined there so I'm puzzled as to why ghc is complaining.

Else can you post a gist of the file you are running through liquid?

Thanks!

**Comment by ranjitjhala** [comment]
Ok got it! Looks like you created a NEW file, and copied the CODE for ==> over but didn't copy the SPEC over; that is shown at the top of the file over here

https://github.com/ucsd-progsys/liquidhaskell-tutorial/blob/master/src/02-logic.lhs#L10

So you should add that in addition to the code for ==> 
From here

https://github.com/ucsd-progsys/liquidhaskell-tutorial/blob/master/src/02-logic.lhs#L132

(I didn't show the spec in chapter 2 because refinement types are only properly introduced in ch 3)
And yet I wanted to sneak them in just to get tangible feedback for the logical queries and validity.

Apologies for the confusion!

**Comment by chowells79** [comment]
That's exactly the issue - I created a new file in which to do the exercises from the chapter.
